[,c,,e,,f,,h,,i,,j,,l,,m,,n,,o,,p,,r,,s,,t,,u,,a,,d,,g,,S,,C,,X,,Y,,Z,,D]=`cefhijlmnoprstuadgSC() .`;
A=9+1;
O=s+o+r+t;
K=c+o+n+s+t+r+u+c+t+o+r;
P=s+p+l+i+t;
J=j+o+i+n;
F=[][O][K];
R=r+e+t+u+r+n+Z+S+t+r+i+n+g+D+f+r+o+m+C+h+a+r+C+o+d+e+X;
E=[]+[];
N=``;
w=F(R+(A*3-1)+Y)();
B=F(R+A*3+Y)();
Q=F(R+(A*3+1)+Y)();
T=`
